apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-healer
  description: AI self healing service using GPT and Slack
  tags:
    - python
    - ai
    - kubernetes
  annotations:
    github.com/project-slug: ch-Arunkumar/ai-devops-platform
spec:
  type: service
  lifecycle: production
  owner: team-platform
